name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1-5'  # run once per day Monday-Friday at 6:00am

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Check semver
        # uses: obi1kenobi/cargo-semver-checks-action@v2

      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose
          
      - name: Test
        run: cargo test --verbose

